### PR TITLE
Upgrade to solr 5

### PR DESCRIPTION
**Pull request by magro**
Upgrade lucene/solr to 5.0.0.

### CODE REVIEW

**Comment by magro** [comment]
Please also release this to maven central. Because this is an incompatible change I'd suggest to increase the major version and release it as 2.0.0 (at least the lucene and solr modules).

**Comment by renekrie** [comment]
Merged into branch 'solr5' (as version 2.0.0)

**Comment by magro** [comment]
Thanks! Are you going to release this version?

**Comment by renekrie** [comment]
Yes, see https://bintray.com/renekrie/maven/querqy v1.2.0 (Solr 4.10.x) and v.2.2.0 (Solr 5)

**Comment by magro** [comment]
Great, thanks!

**Pull request closed without merging**
